### ISSUE TITLE
How exactly to run the benchmarks on Android?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [renatoathaydes/kotlin-hidden-costs-benchmark#1]

**Comment by renatoathaydes** [comment]
See https://willowtreeapps.com/ideas/kotlins-hidden-costs-android-benchmarks

**Comment by AndroidDeveloperLB** [comment]
So he usually got worse results on Kotlin.
There are some articles saying Kotlin performance was improved on Android P.
Do you think it will be noticeable ?

**Comment by renatoathaydes** [comment]
I don't use Android, so I can not answer that. Try to contact the Android blog post author.

**Comment by AndroidDeveloperLB** [comment]
I see. Here's what I got on Pixel 2 with Android P DP5 :

![image](https://user-images.githubusercontent.com/5357526/43287339-773ed74c-912d-11e8-8654-0a6724156e68.png)


I think it's similar to what you guys got, no? Kotlin usually does worse, sadly...
